### ISSUE TITLE
[BUG] Can't parse flow sequence/mapping in single pair flow mapping

### ISSUE THREAD

**Issue by autopp** [saphyr-rs/saphyr-parser#1]
## About

When single pair flow mapping (brace omited flow map in flow sequence) has flow sequence/mapping in value, parser fails.

(Single pair flow mapping is described [here](https://yaml.org/spec/1.2.2/#742-flow-mappings))

## Reproduction

To explain, I use `saphyr`'s `YamlLoader::load_from_str()`.

```rust
use saphyr::YamlLoader;

fn main() {
    let block_style = r#"
- a:
  - 42
"#;

    // Pass
    assert_eq!(
        YamlLoader::load_from_str(block_style),
        YamlLoader::load_from_str("[{a: [42]}]") // innner flow map is sorrounded by {}
    );

    // Should pass, but fails
    assert_eq!(
        YamlLoader::load_from_str(block_style),
        YamlLoader::load_from_str("[a: [42]]") // innner flow map isn't sorrounded by {}
    );
}
```

### Expected behavior

Both assertions pass.

### Actual behavior

The second assertion fails.
```text
thread 'main' panicked at src/main.rs:16:5:
assertion `left == right` failed
  left: Ok([Array([Hash({String("a"): Array([Integer(42)])})])])
 right: Err(ScanError { mark: Marker { index: 7, line: 1, col: 7 }, info: "while parsing a flow sequence, expected ',' or ']'" })
```

Same error occurs for flow map like `"[a: {b: 42}]"`.

## Environment

- Cargo: 1.79.0
- saphyr-parser: 0.2.0

**Comment by Ethiraric** [comment]
Thank you for your report and all the details you've included! Helped me progress much faster.

The scanner appears to return a `FlowMappingEnd` event out of nowhere. It doesn't even match the last `Start` event emitted, which was for a sequence.

I'll take a look during the week :)

**Comment by Ethiraric** [comment]
That was a very good catch, which in the end was much more complicated to solve than I anticipated.

I fiddled with your input and added a bunch of input strings that more thoroughly test the underlying issue you were facing.

Do you need that published on crates.io or can I wait before releasing 0.0.3?

**Comment by autopp** [comment]
Thx for working!
> Do you need that published on crates.io or can I wait before releasing 0.0.3?

I can wait 0.0.3 (This is a syntax sugar, so it is not difficult to avoid this problem)
