### ISSUE TITLE
[BUG] Can't parse block style multiple lines when indent size is greater than 16

### ISSUE THREAD

**Issue by autopp** [saphyr-rs/saphyr-parser#2]
## About

When the indent size is greater than 16, parser can't parses the block style multiple lines scalar.

## Reproduction

```rust
use saphyr_parser::{Event, MarkedEventReceiver, Marker};

struct TestReceiver {}

impl MarkedEventReceiver for TestReceiver {
    fn on_event(&mut self, _ev: Event, _mark: Marker) {}
}

#[test]
fn test_block_scalar01() {
    // block scalar with 1 spaces indent
    let src = r#"
x: |
 a
 b
"#;
    let mut parser = saphyr_parser::parser::Parser::new_from_str(src);
    assert_eq!(Ok(()), parser.load(&mut TestReceiver {}, false));
}

#[test]
fn test_block_scalar02() {
    // block scalar with 2 spaces indent
    let src = r#"
x: |
  a
  b
"#;
    let mut parser = saphyr_parser::parser::Parser::new_from_str(src);
    assert_eq!(Ok(()), parser.load(&mut TestReceiver {}, false));
}

// test_block_scalar03 ~ test_block_scalar019 are omitted

#[test]
fn test_block_scalar20() {
    // block scalar with 20 spaces indent
    let src = r#"
x: |
                    a
                    b
"#;
    let mut parser = saphyr_parser::parser::Parser::new_from_str(src);
    assert_eq!(Ok(()), parser.load(&mut TestReceiver {}, false));
}
```

`test_block_scalarXX()` parses the block style multiple lines scalar with XX spaces indent.

Full version is [here](https://gist.github.com/autopp/70f1e43250909d72ff5ccc2182790d78)

### Expected behavior

All test cases pass.

### Actual behavior

`test_block_scalar01` to `test_block_scalar16` passed.
But `test_block_scalar17` to `test_block_scalar20` failed.

```
---- test_block_scalar17 stdout ----
thread 'test_block_scalar17' panicked at src/bin/block.rs:227:5:
assertion `left == right` failed
  left: Ok(())
 right: Err(ScanError { mark: Marker { index: 42, line: 4, col: 17 }, info: "while parsing a block mapping, did not find expected key" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_block_scalar18 stdout ----
thread 'test_block_scalar18' panicked at src/bin/block.rs:240:5:
assertion `left == right` failed
  left: Ok(())
 right: Err(ScanError { mark: Marker { index: 44, line: 4, col: 18 }, info: "while parsing a block mapping, did not find expected key" })

---- test_block_scalar19 stdout ----
thread 'test_block_scalar19' panicked at src/bin/block.rs:253:5:
assertion `left == right` failed
  left: Ok(())
 right: Err(ScanError { mark: Marker { index: 46, line: 4, col: 19 }, info: "while parsing a block mapping, did not find expected key" })

---- test_block_scalar20 stdout ----
thread 'test_block_scalar20' panicked at src/bin/block.rs:266:5:
assertion `left == right` failed
  left: Ok(())
 right: Err(ScanError { mark: Marker { index: 48, line: 4, col: 20 }, info: "while parsing a block mapping, did not find expected key" })
```

## Environment

Cargo: 1.79.0
saphyr-parser: 2dab0f7 (latest commit)

## Memo

This behavior seems to relate to the buffer of scanner.
https://github.com/saphyr-rs/saphyr-parser/blob/2dab0f70efdffe92ac68c6197653f2775e50528b/src/scanner.rs#L356
https://github.com/saphyr-rs/saphyr-parser/blob/2dab0f70efdffe92ac68c6197653f2775e50528b/src/scanner.rs#L382

When I change [`BUFFER_LEN`](https://github.com/saphyr-rs/saphyr-parser/blob/2dab0f70efdffe92ac68c6197653f2775e50528b/src/scanner.rs#L356) to 17, `test_block_scalar17` pass (But `test_block_scalar18` to `test_block_scalar20` still fail).

**Comment by Ethiraric** [comment]
Thanks again for the very detailed report! It's amazing!

The fault is entirely on me for  this one, and I'm sorry you spent time looking into it.

This issue popped up in `yaml-rust2` and I seemingly failed to port the fix here. The issue lies not with the `BUFFER_LEN` constant, but rather the code reading the whitespace. It attempts to read at most `BUFFER_LEN` whitespace, and falls back to a loop if there are more than that. The error is in a condition in that loop.

Edit: Turns out I just fixed it in my WIP branch.
